// Package sonarqube provides helpers for running SonarQube analysis and
// converting the results into gateway.Diagnostic values.
package sonarqube

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strconv"
	"strings"
	"time"

	"github.com/hiiamtrong/smart-code-review/internal/gateway"
)

// SonarConfig holds the parameters needed to run an analysis.
type SonarConfig struct {
	HostURL          string
	Token            string
	ProjectKey       string
	FilterChanged    bool // only report issues on changed lines
	BlockHotspots    bool // exit 1 on security hotspots
	IsCI             bool // true in GitHub Actions
	BaseBranch       string
	PRNumber         string
	PRHeadBranch     string
}

// Result is the structured outcome of a completed analysis.
type Result struct {
	Diagnostics  []gateway.Diagnostic
	HotspotCount int
	Truncated    bool // true if results hit the page limit (500) and may be incomplete
}

// ─── scanner discovery ────────────────────────────────────────────────────────

// FindScanner returns the path to the sonar-scanner binary.
// Looks in PATH, then ~/. sonar/sonar-scanner/bin/.
func FindScanner() (string, error) {
	name := "sonar-scanner"
	if runtime.GOOS == "windows" {
		name = "sonar-scanner.bat"
	}

	// 1. PATH
	if path, err := exec.LookPath(name); err == nil {
		return path, nil
	}
	if runtime.GOOS != "windows" {
		if path, err := exec.LookPath("sonar-scanner-cli"); err == nil {
			return path, nil
		}
	}

	// 2. ~/.sonar/sonar-scanner/bin/
	home, _ := os.UserHomeDir()
	candidate := filepath.Join(home, ".sonar", "sonar-scanner", "bin", name)
	if _, err := os.Stat(candidate); err == nil {
		return candidate, nil
	}
	// fallback without .bat extension
	candidate2 := filepath.Join(home, ".sonar", "sonar-scanner", "bin", "sonar-scanner")
	if _, err := os.Stat(candidate2); err == nil {
		return candidate2, nil
	}

	return "", fmt.Errorf("sonar-scanner not found in PATH or ~/.sonar/sonar-scanner/bin/; install from https://docs.sonarsource.com/sonarqube/latest/analyzing-source-code/scanners/sonarscanner/")
}

// ─── properties auto-generation ──────────────────────────────────────────────

// AutoGenerateProperties writes a minimal sonar-project.properties to root
// if one does not already exist. Returns the path written (or existing) and
// whether the file was newly created (true) or already existed (false).
func AutoGenerateProperties(root, projectKey string) (string, bool, error) {
	propsPath := filepath.Join(root, "sonar-project.properties")
	if _, err := os.Stat(propsPath); err == nil {
		return propsPath, false, nil // already exists
	}

	if projectKey == "" {
		projectKey = sanitizeKey(filepath.Base(root))
	}

	exclusions := strings.Join([]string{
		"**/node_modules/**", "**/dist/**", "**/build/**",
		"**/target/**", "**/vendor/**",
		"**/*.test.js", "**/*.spec.ts", "**/*.test.ts", "**/*.spec.js",
	}, ",")

	var sb strings.Builder
	fmt.Fprintf(&sb, "# SonarQube Configuration (auto-generated by ai-review)\n")
	fmt.Fprintf(&sb, "sonar.projectKey=%s\n", projectKey)
	fmt.Fprintf(&sb, "sonar.projectName=%s\n", filepath.Base(root))
	fmt.Fprintf(&sb, "sonar.projectVersion=1.0\n")
	fmt.Fprintf(&sb, "sonar.sources=.\n")
	fmt.Fprintf(&sb, "sonar.exclusions=%s\n", exclusions)
	fmt.Fprintf(&sb, "sonar.sourceEncoding=UTF-8\n")
	fmt.Fprintf(&sb, "sonar.scm.provider=git\n")

	// Language-specific extras.
	if exists(filepath.Join(root, "package.json")) {
		sb.WriteString("sonar.javascript.lcov.reportPaths=coverage/lcov.info\n")
		sb.WriteString("sonar.typescript.lcov.reportPaths=coverage/lcov.info\n")
	} else if exists(filepath.Join(root, "pom.xml")) || exists(filepath.Join(root, "build.gradle")) {
		sb.WriteString("sonar.java.binaries=target/classes,build/classes\n")
	} else if exists(filepath.Join(root, "go.mod")) {
		sb.WriteString("sonar.go.coverage.reportPaths=coverage.out\n")
	}

	if err := os.WriteFile(propsPath, []byte(sb.String()), 0644); err != nil {
		return "", false, fmt.Errorf("write sonar-project.properties: %w", err)
	}
	return propsPath, true, nil
}

// Cleanup removes SonarQube artifacts left in the project directory after analysis.
// If propsCreated is true, the auto-generated sonar-project.properties is also removed.
func Cleanup(root string, propsCreated bool) {
	if propsCreated {
		os.Remove(filepath.Join(root, "sonar-project.properties"))
	}
	os.RemoveAll(filepath.Join(root, ".scannerwork"))
	os.Remove(filepath.Join(root, ".sonar_lock"))
}

// ─── analysis execution ───────────────────────────────────────────────────────

// RunAnalysis runs the sonar-scanner binary with the appropriate options.
// stdout and stderr are forwarded to the caller (suppressed at WARN+ level).
func RunAnalysis(scannerBin string, cfg SonarConfig, stagedFiles []string) error {
	args := []string{
		"-Dsonar.host.url=" + cfg.HostURL,
		"-Dsonar.log.level=WARN",
		"-Dsonar.verbose=false",
	}

	if cfg.IsCI {
		if cfg.PRNumber != "" && cfg.PRHeadBranch != "" && cfg.BaseBranch != "" {
			args = append(args,
				"-Dsonar.pullrequest.key="+cfg.PRNumber,
				"-Dsonar.pullrequest.branch="+cfg.PRHeadBranch,
				"-Dsonar.pullrequest.base="+cfg.BaseBranch,
			)
		}
	} else {
		// Local pre-commit: narrow sources to changed dirs.
		args = append(args,
			"-Dsonar.scm.disabled=true",
			"-Dsonar.qualitygate.wait=false",
			"-Dsonar.cpd.exclusions=**/*",
		)
		if len(stagedFiles) > 0 {
			inclusions := strings.Join(stagedFiles, ",")
			dirs := dedupedDirs(stagedFiles)
			args = append(args,
				"-Dsonar.sources="+dirs,
				"-Dsonar.inclusions="+inclusions,
			)
		}
	}

	cmd := exec.Command(scannerBin, args...) //nolint:gosec
	cmd.Env = append(os.Environ(), "SONAR_TOKEN="+cfg.Token)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("sonar-scanner failed: %w", err)
	}
	return nil
}

// ─── task polling ─────────────────────────────────────────────────────────────

// WaitForTask polls the SonarQube background task until it completes or times out.
// It reads the ceTaskId from .scannerwork/report-task.txt.
func WaitForTask(hostURL, token, repoRoot string, isCI bool) error {
	reportFile := filepath.Join(repoRoot, ".scannerwork", "report-task.txt")
	taskID := readTaskID(reportFile)
	if taskID == "" {
		// No task ID — wait a fixed time for the analysis to complete.
		time.Sleep(3 * time.Second)
		return nil
	}

	maxWait := 30 * time.Second
	if isCI {
		maxWait = 60 * time.Second
	}
	pollInterval := 1 * time.Second
	if isCI {
		pollInterval = 2 * time.Second
	}

	deadline := time.Now().Add(maxWait)
	url := fmt.Sprintf("%s/api/ce/task?id=%s", hostURL, taskID)

	for time.Now().Before(deadline) {
		status, err := fetchTaskStatus(url, token)
		if err == nil {
			switch status {
			case "SUCCESS":
				return nil
			case "FAILED":
				return fmt.Errorf("SonarQube analysis task failed")
			case "CANCELED":
				return fmt.Errorf("SonarQube analysis task was canceled")
			}
		}
		time.Sleep(pollInterval)
	}
	// Timed out — proceed anyway (results may be partial).
	return nil
}

// ─── results fetching ─────────────────────────────────────────────────────────

// FetchResults retrieves issues and hotspots from the SonarQube API and returns
// them as gateway.Diagnostic values filtered to changedFiles if requested.
func FetchResults(cfg SonarConfig, changedLineRanges []lineRange) (*Result, error) {
	// Issues.
	issuesURL := fmt.Sprintf("%s/api/issues/search?componentKeys=%s&resolved=false&ps=500",
		cfg.HostURL, cfg.ProjectKey)
	issues, err := fetchIssues(issuesURL, cfg.Token)
	if err != nil {
		return nil, fmt.Errorf("fetch issues: %w", err)
	}

	diagnostics := convertIssues(issues, cfg.HostURL)

	// Filter to changed lines if requested.
	if cfg.FilterChanged && len(changedLineRanges) > 0 {
		diagnostics = filterByChangedLines(diagnostics, changedLineRanges)
	}

	// Hotspots.
	hotspotsURL := fmt.Sprintf("%s/api/hotspots/search?projectKey=%s&status=TO_REVIEW&ps=500",
		cfg.HostURL, cfg.ProjectKey)
	hotspotCount, hotspotsTruncated := fetchHotspotCount(hotspotsURL, cfg.Token)

	return &Result{
		Diagnostics:  diagnostics,
		HotspotCount: hotspotCount,
		Truncated:    len(issues) >= 500 || hotspotsTruncated,
	}, nil
}

// ─── changed-line helpers ─────────────────────────────────────────────────────

type lineRange struct {
	File  string
	Start int
	End   int
}

// ParseStagedLineRanges extracts changed line ranges from `git diff --cached -U0` output.
func ParseStagedLineRanges(diff string) []lineRange {
	var ranges []lineRange
	var currentFile string
	hunkRe := regexp.MustCompile(`^@@ -\d+(?:,\d+)? \+(\d+)(?:,(\d+))? @@`)

	for _, line := range strings.Split(diff, "\n") {
		if strings.HasPrefix(line, "diff --git ") {
			parts := strings.Fields(line)
			if len(parts) >= 4 {
				currentFile = strings.TrimPrefix(parts[3], "b/")
			}
			continue
		}
		if m := hunkRe.FindStringSubmatch(line); m != nil && currentFile != "" {
			start, _ := strconv.Atoi(m[1])
			count := 1
			if m[2] != "" {
				count, _ = strconv.Atoi(m[2])
			}
			if count == 0 {
				continue // deletion-only hunk
			}
			ranges = append(ranges, lineRange{File: currentFile, Start: start, End: start + count - 1})
		}
	}
	return ranges
}

// ─── internal helpers ─────────────────────────────────────────────────────────

func filterByChangedLines(diags []gateway.Diagnostic, ranges []lineRange) []gateway.Diagnostic {
	var out []gateway.Diagnostic
	for _, d := range diags {
		for _, r := range ranges {
			if d.Location.Path == r.File &&
				d.Location.Range.Start.Line >= r.Start &&
				d.Location.Range.Start.Line <= r.End {
				out = append(out, d)
				break
			}
		}
	}
	return out
}

type sonarIssue struct {
	Message   string `json:"message"`
	Rule      string `json:"rule"`
	Severity  string `json:"severity"`
	Component string `json:"component"`
	Line      int    `json:"line"`
}

func fetchIssues(url, token string) ([]sonarIssue, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	req, _ := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	req.SetBasicAuth(token, "")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var result struct {
		Issues []sonarIssue `json:"issues"`
	}
	body, _ := io.ReadAll(resp.Body)
	if err := json.Unmarshal(body, &result); err != nil {
		return nil, fmt.Errorf("parse issues response: %w", err)
	}
	return result.Issues, nil
}

func convertIssues(issues []sonarIssue, hostURL string) []gateway.Diagnostic {
	diags := make([]gateway.Diagnostic, 0, len(issues))
	for _, iss := range issues {
		line := iss.Line
		if line == 0 {
			line = 1
		}
		// Strip the "projectKey:" prefix from component paths.
		path := iss.Component
		if idx := strings.Index(path, ":"); idx >= 0 {
			path = path[idx+1:]
		}

		diags = append(diags, gateway.Diagnostic{
			Message:  fmt.Sprintf("%s [%s]", iss.Message, iss.Rule),
			Severity: sonarToSeverity(iss.Severity),
			Location: gateway.Location{
				Path: path,
				Range: gateway.Range{
					Start: gateway.Position{Line: line, Column: 1},
					End:   gateway.Position{Line: line, Column: 100},
				},
			},
			Code: gateway.Code{
				Value: iss.Rule,
				URL:   fmt.Sprintf("%s/coding_rules?open=%s", hostURL, iss.Rule),
			},
		})
	}
	return diags
}

func sonarToSeverity(s string) string {
	switch s {
	case "BLOCKER", "CRITICAL", "MAJOR":
		return "ERROR"
	case "MINOR":
		return "WARNING"
	default:
		return "INFO"
	}
}

func fetchHotspotCount(url, token string) (int, bool) {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	req, _ := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	req.SetBasicAuth(token, "")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return 0, false
	}
	defer resp.Body.Close()
	var result struct {
		Hotspots []json.RawMessage `json:"hotspots"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return 0, false
	}
	n := len(result.Hotspots)
	return n, n >= 500
}

func fetchTaskStatus(url, token string) (string, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	req, _ := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	req.SetBasicAuth(token, "")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	var result struct {
		Task struct {
			Status string `json:"status"`
		} `json:"task"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return "", err
	}
	return result.Task.Status, nil
}

func readTaskID(reportFile string) string {
	f, err := os.Open(reportFile)
	if err != nil {
		return ""
	}
	defer f.Close()
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, "ceTaskId=") {
			return strings.TrimSpace(strings.TrimPrefix(line, "ceTaskId="))
		}
	}
	return ""
}

func sanitizeKey(name string) string {
	re := regexp.MustCompile(`[^a-zA-Z0-9_-]`)
	return re.ReplaceAllString(name, "_")
}

func exists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func dedupedDirs(files []string) string {
	seen := make(map[string]bool)
	var dirs []string
	for _, f := range files {
		d := filepath.Dir(f)
		if d == "." {
			// "." covers the entire project; no other dirs needed.
			return "."
		}
		if !seen[d] {
			seen[d] = true
			dirs = append(dirs, d)
		}
	}
	// Remove subdirs that have a parent already in the list.
	var deduped []string
	for _, d := range dirs {
		covered := false
		for _, other := range dirs {
			if d != other && strings.HasPrefix(d+"/", other+"/") {
				covered = true
				break
			}
		}
		if !covered {
			deduped = append(deduped, d)
		}
	}
	return strings.Join(deduped, ",")
}
