name: "Smart Code Review"
description: "AI-powered code review with language detection and linting integration"
author: "hiiamtrong"
branding:
  icon: "check-circle"
  color: "green"

inputs:
  github_token:
    description: "GITHUB_TOKEN for posting PR comments"
    required: true
  ai_gateway_url:
    description: "AI Gateway URL for code review"
    required: true
  ai_gateway_api_key:
    description: "API key for AI Gateway"
    required: true
  ai_model:
    description: "AI model to use (default: gemini-2.0-flash)"
    required: false
    default: "gemini-2.0-flash"
  ai_provider:
    description: "AI provider to use (default: google)"
    required: false
    default: "google"

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        echo "Checking and installing required dependencies..."

        # Update package list
        sudo apt-get update

        # Install required packages if not present
        PACKAGES_TO_INSTALL=""

        if ! command -v jq &> /dev/null; then
          PACKAGES_TO_INSTALL="$PACKAGES_TO_INSTALL jq"
        fi

        if ! command -v curl &> /dev/null; then
          PACKAGES_TO_INSTALL="$PACKAGES_TO_INSTALL curl"
        fi

        if ! command -v git &> /dev/null; then
          PACKAGES_TO_INSTALL="$PACKAGES_TO_INSTALL git"
        fi

        if [ -n "$PACKAGES_TO_INSTALL" ]; then
          echo "Installing:$PACKAGES_TO_INSTALL"
          sudo apt-get install -y $PACKAGES_TO_INSTALL
        else
          echo "All required dependencies are already installed"
        fi
    - name: Smart Code Review
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        AI_GATEWAY_URL: ${{ inputs.ai_gateway_url }}
        AI_GATEWAY_API_KEY: ${{ inputs.ai_gateway_api_key }}
        AI_MODEL: ${{ inputs.ai_model }}
        AI_PROVIDER: ${{ inputs.ai_provider }}
      run: |
        bash ${{ github.action_path }}/scripts/detect-language.sh
