#!/usr/bin/env bash
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Installation paths
CONFIG_DIR="$HOME/.config/ai-review"
BIN_DIR="$HOME/.local/bin"
HOOKS_DIR="$CONFIG_DIR/hooks"

echo -e "${BLUE}🚀 AI Review Installer${NC}"
echo "================================"

# Detect OS
detect_os() {
  case "$(uname -s)" in
    Darwin*)
      OS="macos"
      ;;
    Linux*)
      if grep -qi microsoft /proc/version 2>/dev/null; then
        OS="wsl"
      else
        OS="linux"
      fi
      ;;
    *)
      echo -e "${RED}❌ Unsupported operating system${NC}"
      exit 1
      ;;
  esac
  echo -e "${GREEN}✓${NC} Detected OS: $OS"
}

# Install dependencies
install_dependencies() {
  echo -e "\n${BLUE}📦 Checking dependencies...${NC}"

  # Check git
  if ! command -v git &> /dev/null; then
    echo -e "${RED}❌ git is required but not installed${NC}"
    exit 1
  fi
  echo -e "${GREEN}✓${NC} git is installed"

  # Check curl
  if ! command -v curl &> /dev/null; then
    echo -e "${RED}❌ curl is required but not installed${NC}"
    exit 1
  fi
  echo -e "${GREEN}✓${NC} curl is installed"

  # Check/install jq
  if ! command -v jq &> /dev/null; then
    echo -e "${YELLOW}⚠${NC} jq not found, installing..."
    case "$OS" in
      macos)
        if ! command -v brew &> /dev/null; then
          echo -e "${YELLOW}⚠${NC} Homebrew not found, installing..."
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        fi
        brew install jq
        ;;
      linux|wsl)
        sudo apt-get update && sudo apt-get install -y jq
        ;;
    esac
    echo -e "${GREEN}✓${NC} jq installed"
  else
    echo -e "${GREEN}✓${NC} jq is installed"
  fi
}

# Create directories
create_directories() {
  echo -e "\n${BLUE}📁 Creating directories...${NC}"

  mkdir -p "$CONFIG_DIR"
  mkdir -p "$BIN_DIR"
  mkdir -p "$HOOKS_DIR"

  echo -e "${GREEN}✓${NC} Created $CONFIG_DIR"
  echo -e "${GREEN}✓${NC} Created $BIN_DIR"
  echo -e "${GREEN}✓${NC} Created $HOOKS_DIR"
}

# Get script directory (works for both curl|bash and direct execution)
get_script_source() {
  if [[ -n "$BASH_SOURCE" && -f "$(dirname "${BASH_SOURCE[0]}")/ai-review" ]]; then
    # Direct execution - files are alongside install.sh
    SCRIPT_SOURCE="local"
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  else
    # Remote execution via curl|bash - download from repo
    SCRIPT_SOURCE="remote"
    REPO_URL="https://raw.githubusercontent.com/user/smart-code-review/main"
  fi
}

# Install CLI and hook scripts
install_scripts() {
  echo -e "\n${BLUE}📥 Installing scripts...${NC}"

  get_script_source

  if [[ "$SCRIPT_SOURCE" == "local" ]]; then
    # Copy from local source
    cp "$SCRIPT_DIR/ai-review" "$BIN_DIR/ai-review"
    cp "$SCRIPT_DIR/pre-commit.sh" "$HOOKS_DIR/pre-commit.sh"
  else
    # Download from remote
    curl -sSL "$REPO_URL/scripts/local/ai-review" -o "$BIN_DIR/ai-review"
    curl -sSL "$REPO_URL/scripts/local/pre-commit.sh" -o "$HOOKS_DIR/pre-commit.sh"
  fi

  chmod +x "$BIN_DIR/ai-review"
  chmod +x "$HOOKS_DIR/pre-commit.sh"

  echo -e "${GREEN}✓${NC} Installed ai-review CLI to $BIN_DIR/ai-review"
  echo -e "${GREEN}✓${NC} Installed hook template to $HOOKS_DIR/pre-commit.sh"
}

# Interactive configuration
configure_credentials() {
  echo -e "\n${BLUE}⚙️  Configuration${NC}"
  echo "Please provide your AI Gateway credentials:"
  echo ""

  # AI Gateway URL
  read -p "Enter AI Gateway URL: " AI_GATEWAY_URL
  while [[ -z "$AI_GATEWAY_URL" ]]; do
    echo -e "${RED}URL is required${NC}"
    read -p "Enter AI Gateway URL: " AI_GATEWAY_URL
  done

  # AI Gateway API Key
  read -sp "Enter AI Gateway API Key: " AI_GATEWAY_API_KEY
  echo ""
  while [[ -z "$AI_GATEWAY_API_KEY" ]]; do
    echo -e "${RED}API Key is required${NC}"
    read -sp "Enter AI Gateway API Key: " AI_GATEWAY_API_KEY
    echo ""
  done

  # AI Model (optional)
  read -p "Enter AI Model [gemini-2.0-flash]: " AI_MODEL
  AI_MODEL="${AI_MODEL:-gemini-2.0-flash}"

  # AI Provider (optional)
  read -p "Enter AI Provider [google]: " AI_PROVIDER
  AI_PROVIDER="${AI_PROVIDER:-google}"

  # Save config
  cat > "$CONFIG_DIR/config" << EOF
# AI Review Configuration
# Generated by installer on $(date)

AI_GATEWAY_URL="$AI_GATEWAY_URL"
AI_GATEWAY_API_KEY="$AI_GATEWAY_API_KEY"
AI_MODEL="$AI_MODEL"
AI_PROVIDER="$AI_PROVIDER"
EOF

  chmod 600 "$CONFIG_DIR/config"
  echo -e "\n${GREEN}✓${NC} Configuration saved to $CONFIG_DIR/config"
}

# Add to PATH
setup_path() {
  echo -e "\n${BLUE}🔧 Setting up PATH...${NC}"

  # Check if already in PATH
  if echo "$PATH" | grep -q "$BIN_DIR"; then
    echo -e "${GREEN}✓${NC} $BIN_DIR is already in PATH"
    return
  fi

  # Detect shell config file
  SHELL_CONFIG=""
  if [[ -n "$ZSH_VERSION" ]] || [[ "$SHELL" == *"zsh"* ]]; then
    SHELL_CONFIG="$HOME/.zshrc"
  elif [[ -n "$BASH_VERSION" ]] || [[ "$SHELL" == *"bash"* ]]; then
    if [[ -f "$HOME/.bashrc" ]]; then
      SHELL_CONFIG="$HOME/.bashrc"
    elif [[ -f "$HOME/.bash_profile" ]]; then
      SHELL_CONFIG="$HOME/.bash_profile"
    fi
  fi

  if [[ -n "$SHELL_CONFIG" ]]; then
    # Check if export already exists
    if ! grep -q "export PATH=\"\$HOME/.local/bin:\$PATH\"" "$SHELL_CONFIG" 2>/dev/null; then
      echo "" >> "$SHELL_CONFIG"
      echo "# Added by ai-review installer" >> "$SHELL_CONFIG"
      echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$SHELL_CONFIG"
      echo -e "${GREEN}✓${NC} Added $BIN_DIR to PATH in $SHELL_CONFIG"
    else
      echo -e "${GREEN}✓${NC} PATH export already exists in $SHELL_CONFIG"
    fi
  else
    echo -e "${YELLOW}⚠${NC} Could not detect shell config file"
    echo "Please add the following to your shell config:"
    echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
  fi
}

# Print success message
print_success() {
  echo ""
  echo -e "${GREEN}================================${NC}"
  echo -e "${GREEN}✅ Installation complete!${NC}"
  echo -e "${GREEN}================================${NC}"
  echo ""
  echo "Next steps:"
  echo "  1. Restart your terminal or run: source ~/.zshrc (or ~/.bashrc)"
  echo "  2. Navigate to any git repository"
  echo "  3. Run: ai-review install"
  echo ""
  echo "Available commands:"
  echo "  ai-review install    - Install hook in current repo"
  echo "  ai-review uninstall  - Remove hook from current repo"
  echo "  ai-review config     - View/edit configuration"
  echo "  ai-review status     - Check installation status"
  echo "  ai-review update     - Update to latest version"
  echo "  ai-review help       - Show help"
  echo ""
}

# Main installation flow
main() {
  detect_os
  install_dependencies
  create_directories
  install_scripts
  configure_credentials
  setup_path
  print_success
}

main
